name: main build

on:
  push:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    
    
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:    
      
    - uses: actions/checkout@v2
    - name: Setup .NET  
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./SplashRentals.sln
      
    - name: Build
      run: dotnet build ./SplashRentals.sln
      
    - name: Test
      run: dotnet test ./SplashRentals.sln
